homepage:
    path: /{_locale}
    controller: App\Infrastructure\Controller\Home\HomeController::index
    defaults:
        template: home/index.html.twig
        _locale: '%locale%'

controllers:
    resource:
        path: ../src/Infrastructure/Controller/
        namespace: App\Infrastructure\Controller
    type: attribute

    prefix: /{_locale}
    defaults:
        # If set url will be / on default locale. In example:
        #   default locale - en
        #   expects home url - /en
        #   will be - /
        #_locale: '%locale%'
    
    trailing_slash_on_root: false