controllers:
    resource:
        path: ../src/Infrastructure/Controller/
        namespace: App\Infrastructure\Controller
    type: attribute

    prefix: /{_locale}
    defaults:
        _locale: '%locale%'