homepage:
    path: /{_locale}
    controller: App\Infrastructure\Controller\Home\HomeController::index
    defaults:
        template: home/index.html.twig
        _locale: '%locale%'

controllers:
    resource:
        path: ../src/Infrastructure/Controller/
        namespace: App\Infrastructure\Controller
    type: attribute

    prefix: /{_locale}
    defaults:
        _locale: '%locale%'